a = [
    "Chenin blanc",
    "Melon de bourgogne",
    "Savagnin",
    "Petit manseng",
    "baco",
    "Chardonnay",
    "Pinot Meunier",
    "Macabeo",
    "Pinot noir",
    "Carmenère.",
    "La_folle_blanche",
    "Gros manseng",
    "Malbec.",
    "Furmint",
    "Corvina",
    "Muscat",
    "Petit Verdot",
    "Mourvedre",
    "De Cabernet Sauvignon",
    "Nerello Mascalese",
    "Nerello cappucio",
    "Sangiovese",
    "Mondeuse blanche",
    "Sauvignon blanc",
    "Roussanne",
    "Sylvaner",
    "Lauzet",
    "Gibert",
    "Pinot",
    "De Petit Verdot",
    "Grenache",
    "Merlot",
    "Muscat blanc à petits grains",
    "Tempranillo",
    "Muscardin",
    "Pinot Gris",
    "Sauvignon Gris",
    "Syrah",
    "Petit Verdot.",
    "Cabernet Sauvignon",
    "Négrette",
    "Cabernet sauvignon",
    "Macabeu",
    "Pinot meunier",
    "De Cabernet Franc",
    "Merlot.",
    "Muscadelle",
    "cépage blanc bourguignon",
    "Pinot Noir",
    "Marsanne",
    "Mourvèdre",
    "Pinot blanc",
    "Colombard",
    "Grenache noir",
    "Cinsault",
    "cabernet franc",
    "Riesling",
    "Terret noir",
    "Petit verdot",
    "Semillon",
    "Persan",
    "Pelavergua piccolo",
    "Cabernet Franc.",
    "Vaccarèse",
    "Gros Manseng",
    "Pinot Menier",
    "Baco",
    "Mourvèdre et Sangiovese",
    "Uugni",
    "Dolcetto",
    "Zinfandel",
    "Barbera",
    "Chenin Blan",
    "Nero d Avola",
    "Gamay",
    "Valdiguié",
    "Carménère",
    "De Merlot",
    "Gewurztraminer",
    "Cabernet franc",
    "Aligoté",
    "Romorantin",
    "Sauvignon Blanc",
    "Sémillon",
    "Counoise",
    "Cabernet Franc",
    "Noual",
    "Camaralet",
    "Carmenère",
    "Jacquère",
    "Chenin Blanc",
    "Pineau d Aunis",
    "Ugni blanc",
    "Poulsar",
    "Carignan",
    "Gewurztra",
    "Folle blanche",
    "Douce Noire",
    "Nebbiolo",
    "ugni blanc",
    "Malbec",
    "aligoté",
    "Jurançon noir",
    "Pinot gris",
    "Trousseau",
    "Bourboulenc",
    "Nerello mascalese",
    "Poulsard",
    "Trebbiano",
    "Sauvignon",
    "Barbarossa",
    "Nerello Cappucio",
    "Merlot (Pas De Petit Verdot Dans Ce Millésime)",
    "Cartoixa",
    "Melon de Bourgogne",
    "Clairette",
    "Mondeuse",
    "Viognier",
]

a.sort()
print(a)
# remove les points
# bien tout mettre en title

b = [
    "Aligoté",
    "Baco",
    "Barbarossa",
    "Barbera",
    "Bourboulenc",
    "Cabernet Franc",
    "Cabernet Franc.",
    "Cabernet Sauvignon",
    "Cabernet franc",
    "Cabernet sauvignon",
    "Camaralet",
    "Carignan",
    "Carmenère",
    "Carmenère.",
    "Carménère",
    "Cartoixa",
    "Chardonnay",
    "Chenin Blan",  # error
    "Chenin Blanc",
    "Chenin blanc",
    "Cinsault",
    "Clairette",
    "Colombard",
    "Corvina",
    "Counoise",
    "De Cabernet Franc",  # hmm
    "De Cabernet Sauvignon",  # hmmm
    "De Merlot",
    "De Petit Verdot",  # hmmm POurquoi "De" à chaque fois
    "Dolcetto",
    "Douce Noire",
    "Folle blanche",
    "Furmint",
    "Gamay",
    "Gewurztra",
    "Gewurztraminer",  # ce sont les memes
    "Gibert",
    "Grenache",
    "Grenache noir",
    "Gros Manseng",  # title
    "Gros manseng",
    "Jacquère",
    "Jurançon noir",
    "La_folle_blanche",  # à traiter
    "Lauzet",
    "Macabeo",  # ce ston les mêmes (variante ortho)
    "Macabeu",
    "Malbec",
    "Malbec.",  # .
    "Marsanne",
    "Melon de Bourgogne",  # title
    "Melon de bourgogne",
    "Merlot",
    "Merlott",
    "Merlot (Pas De Petit Verdot Dans Ce Millésime)",  # hmmm
    "Merlot.",  # .
    "Mondeuse",  # mondeuse noir et mondeuse blanche
    "Mondeuse blanche",
    "Mourvedre",  # accent
    "Mourvèdre",
    "Mourvèdre et Sangiovese",  # erreur ici
    "Muscadelle",
    "Muscardin",
    "Muscat",
    "Muscat blanc à petits grains",  # hmm meme hose, apparement le plus ancien
    "Nebbiolo",
    "Nerello Cappucio",
    "Nerello cappucio",  # title
    "Nerello Mascalese",
    "Nerello mascalese",  # title
    "Nero d Avola",
    "Noual",
    "Négrette",
    "Pelavergua piccolo",
    "Persan",
    "Petit Verdot",
    "Petit Verdot.",  # .
    "Petit manseng",
    "Petit verdot",  # title
    "Pineau d Aunis",
    "Pinot",
    "Pinot Gris",
    "Pinot Menier",
    "Pinot Meunier",
    "Pinot Noir",
    "Pinot blanc",
    "Pinot gris",
    "Pinot meunier",
    "Pinot noir",  # title
    "Poulsar",  # error
    "Poulsard",
    "Riesling",
    "Romorantin",
    "Roussanne",
    "Sangiovese",
    "Sauvignon",
    "Sauvignon Blanc",
    "Sauvignon blanc",  # title
    "Sauvignon Gris",
    "Savagnin",
    "Semillon",
    "Sylvaner",
    "Syrah",
    "Sémillon",
    "Tempranillo",
    "Terret noir",
    "Trebbiano",
    "Trousseau",
    "Ugni blanc",  # title = Trebianno
    "Uugni",  # error = trebbiano
    "Vaccarèse",
    "Valdiguié",
    "Viognier",
    "Zinfandel",
    "aligoté",  # title, existe déja la haut
    "baco",
    "cabernet franc",  # title...
    "cépage blanc bourguignon",  # ghmmmm
    "ugni blanc",  # title
]
